---
title: "GraphTheory"
output: html_document
---



```{r}
library("igraph")


```
```{r}
#Creating dataframe
friends <- data.frame(list(name1 = c("Jessie", "Jessie", "Sidney", "Sidney", "Karl", "Sidney", "Britt" , "Shayne","Sidney", "Sidney" ,"Jessie", "Donnie" ,"Sidney" ,"Rene" , "Shayne", "Jessie","Rene",  "Elisha", "Eugene", "Berry"  ,"Odell",  "Odell","Britt" , "Elisha", "Lacy" ,  "Britt",  "Karl"), name2 = c("Sidney", "Britt", "Britt" ,  "Donnie" , "Berry","Rene" ,   "Rene" ,"Sidney" , "Elisha" , "Whitney" ,"Whitney", "Odell" ,  "Odell"  , "Whitney","Donnie" , "Lacy", "Lacy",    "Eugene" , "Jude"  ,  "Odell" ,  "Rickie","Karl"  ,  "Lacy" ,   "Jude"  ,  "Whitney" ,"Whitney" ,"Tommy")))
```


```{r}
#Inspection and converting df in matrix
head(friends)
newfriends <- as.matrix(friends)

```
```{r}
#Converting matrix into igraoh object
g <- graph.edgelist(newfriends, directed = FALSE)
plot(g)
```
```{r}
#counting number of edges and vertices
V(g)
E(g)
gsize(g)
gorder(g)
```
```{r}
#adding attributes

gender <- c("M", "F", "F", "M", "M", "M" ,"F" ,"M" ,"M", "F", "M", "F" ,"M" ,"F" ,"M", "M")
age <- c(18, 19, 21 ,20, 22, 18, 23, 21 ,22, 20, 20, 22, 21, 18, 19, 20)

g <- set_vertex_attr(g, "gender", value = gender )

g <- set_vertex_attr(g, "Age", value = age )
#View all vertex attributes using
vertex_attr(g)
#View the attributes of the first five vertices in a dataframe using
V(g)[[1:5]]


```
```{r}
#Edge attributes and subsetting
hours <- c(1, 2, 2, 1, 2 ,5, 5, 1, 1, 3, 2, 1, 1, 5, 1, 2, 4, 1, 3, 1, 1, 1, 4 ,1, 3, 3 ,4)
# Create new edge attribute called 'hours'
g <- set_edge_attr(g,"Hours", value = hours)
# View edge attributes of graph object
edge_attr(g)

# Find all edges that include "Britt"
E(g)[[inc('Britt')]]  

# Find all pairs that spend 4 or more hours together per week
E(g)[[hours>=4]]  
```
```{r}
#visualising attributes
# Create an igraph object with attributes directly from dataframes
friends1_edges <- list(name1 = c("Joe"  ,"Joe"  ,     "Joe"     ,  "Erin" ,     "Kelley",    "Ronald",   
"Ronald",    "Ronald" ,   "Michael" ,  "Michael"  , "Michael"   ,"Valentine", "Troy"    ,  "Troy",      "Jasmine",   "Jasmine"  , "Juan"  ,    "Carey",     "Frankie",   "Frankie",   "Micheal",   "Micheal"  , "Keith" ,    "Keith"    ,"Gregory"), name2 = c("Joe" ,      "Joe"   ,    "Joe",       "Erin"    ,  "Kelley"  ,  "Ronald",   
"Ronald" ,   "Ronald" ,   "Michael",   "Michael"  , "Michael" ,  "Valentine"
, "Troy"  ,    "Troy" ,     "Jasmine",   "Jasmine"  , "Juan"    ,  "Carey",    
 "Frankie"  , "Frankie" ,  "Micheal"  , "Micheal" ,  "Keith"  ,   "Keith",    
 "Gregory"), hours =  c(1 ,3 ,2 ,3 ,5 ,1, 3, 5 ,2 ,1 ,3 ,5 ,3 ,2 ,6 ,1 ,2 ,2, 1 ,1 ,2 ,1, 1 ,3 ,2))

friends1_nodes <- list(name = c("Joe"  ,     "Erin" ,     "Kelley",    "Ronald",    "Michael",   "Valentine",
 "Troy" ,     "Jasmine"   ,"Juan"   ,   "Carey"   ,  "Frankie"  , "Micheal",  
 "Keith",     "Gregory",   "Perry"  ,   "Demetrius", "Merle"  ,   "Alex",     
 "Marion"), gender = c("M", "F", "F", "M", "M" ,"F", "M", "F", "M", "F" ,"F", "M", "M", "M", "M", "M", "M", "F", "F"))

  
g1 <- graph_from_data_frame(d = friends1_edges, vertices = friends1_nodes, directed = FALSE)


# Subset edges greater than or equal to 5 hours
E(g1)[[hours>=5]]  

# Plot network and color vertices by gender
V(g1)$color <- ifelse(V(g1)$gender == "males", "orange", "dodgerblue")
plot(g1, vertex.label.color = "black")
```

```{r}
#network layouts

# Plot the graph object g1 in a circle layout
plot(g1, vertex.label.color = "black", layout = layout_in_circle(g1))

# Plot the graph object g1 in a Fruchterman-Reingold layout 
plot(g1, vertex.label.color = "black", layout = layout_with_fr(g1))

# Plot the graph object g1 in a Tree layout 
m <- layout_as_tree(g1)
plot(g1, vertex.label.color = "black", layout = m )
  
```
```{r}
# Create a vector of weights based on the number of hours each pair spend together
w1 <- E(g1)$hours

# Plot the network varying edges by weights
m1 <- layout_nicely(g1)
plot(g1, 
        vertex.label.color = "black", 
        edge.color = 'black',
        edge.width = w1,
        layout = m1)


# Create a new igraph object only including edges from the original graph that are greater than 2 hours long 
g2 <- delete_edges(g1, E(g1)[hours < 2])


# Plot the new graph 
w2 <- E(g2)$hours
m2 <- layout_nicely(g2)

plot(g2, 
     vertex.label.color = "black", 
     edge.color = 'black',
     edge.width = w2,
     layout = m2)
```





